#!/usr/bin/env bash

if [ -z "$FULL" ];then
	exit
fi


pacman -Sy --noconfirm --needed \
    gcc \
    clang \
    cmake \
    ninja \
    libx11 \
    libxcursor \
    libxi \
    libxrandr \
    mesa-libgl \
    fontconfig \
    libwebp

# =====================
#       ASEPRITE
# =====================
sudo -u "${SUDO_USER:-$USER}" bash <<'EOF'
    git clone --recursive https://github.com/aseprite/aseprite.git aseprite_source
    pushd aseprite_source
    ./build.sh --auto
    popd
EOF
