#!/usr/bin/env bash

pacman -Sy --needed --noconfirm \
    nautilus \
    gstreamer \
    gst-plugins-base \
    gst-plugins-good \
    gst-plugins-bad \
    gst-plugins-ugly \
    gst-libav \
    ffmpegthumbnailer \
    file-roller \
