#!/usr/bin/env bash

pacman -Sy --needed --noconfirm \
	neovim \
	lua-language-server \
	luajit \
	lua51 \
	luarocks \
	fd \
	ripgrep \
	tree-sitter-cli \
	vim-devicons \
	chafa

# non-essential editors, installed only with FULL setup
if [ -z "$FULL" ];then
	exit
fi

pacman -Sy --needed --noconfirm \
    emacs

sudo -u "${SUDO_USER:-$USER}" bash <<'EOF'
    git clone --depth 1 https://github.com/doomemacs/doomemacs $HOME/.config/emacs
    $HOME/.config/emacs/bin/doom install --force
EOF
