#!/usr/bin/env bash

pacman -Sy --needed --noconfirm \
    xclip \
    rsync \
    tldr \
    tree \
    fzf \
    less \
    man-db \
    man-pages \
    samba \
    cifs-utils \
    netcat \
    netstat-nat \
    bat \
    jq \
    lsd \
    ghostty \
    mpv \
    waybar \
    spotify-launcher \
    btop \
    gwenview \
    hyprpaper \
    hyprcursor \
    hyprshot \
    libreoffice \
    transmission-qt \
    transmission-cli

# desktop portal packages, installed only with FULL setup
if [ -z "$FULL" ];then
    exit
fi

# properly displaying pop-ups
pacman -Sy --needed --noconfirm \
    xdg-desktop-portal \
    xdg-desktop-portal-hyprland \
    xdg-desktop-portal-gtk

systemctl --user enable xdg-desktop-portal
systemctl --user restart xdg-desktop-portal

systemctl --user enable xdg-desktop-portal-hyprland
systemctl --user restart xdg-desktop-portal-hyprland

systemctl --user enable xdg-desktop-portal-gtk
systemctl --user restart xdg-desktop-portal-gtk
