preload = $HOME/wallpapers/wallpaper3.jpg
preload = $HOME/wallpapers/wallpaper8.jpg
preload = $HOME/wallpapers/wallpaper9.jpg
preload = $HOME/wallpapers/wallpaper10.jpg
preload = $HOME/wallpapers/wallpaper11.jpg
preload = $HOME/wallpapers/wallpaper19.jpg
preload = $HOME/wallpapers/wallpaper25.jpeg
preload = $HOME/wallpapers/wallpaper29.jpg
preload = $HOME/wallpapers/wallpaper52.jpg
preload = $HOME/wallpapers/wallpaper52.png
preload = $HOME/wallpapers/wallpaper233.png

wallpaper {
    monitor = HDMI-A-1
    path = /home/mohitjangra/wallpapers233.png
    fit_mode = cover
    timeout = 30
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/mohitjangra/wallpapers/wallpaper3.jpg
    fit_mode = cover
    timeout = 30
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/mohitjangra/wallpapers/wallpaper8.jpg
    fit_mode = cover
    timeout = 30
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/mohitjangra/wallpapers/wallpaper9.jpg
    fit_mode = cover
    timeout = 30
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/mohitjangra/wallpapers/wallpaper10.jpg
    fit_mode = cover
    timeout = 30
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/mohitjangra/wallpapers/wallpaper11.jpg
    fit_mode = cover
    timeout = 30
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/mohitjangra/wallpapers/wallpaper19.jpg
    fit_mode = cover
    timeout = 30
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/mohitjangra/wallpapers/wallpaper25.jpeg
    fit_mode = cover
    timeout = 30
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/mohitjangra/wallpapers/wallpaper29.jpg
    fit_mode = cover
    timeout = 30
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/mohitjangra/wallpapers/wallpaper52.jpg
    fit_mode = cover
    timeout = 30
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/mohitjangra/wallpapers/wallpaper52.png
    fit_mode = cover
    timeout = 30
}
